config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help', as: 'help'
  get  '/about',   to: 'static_pages#about', as: 'about'
  get  '/contact', to: 'static_pages#contact', as: 'contact'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login',  to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
   
  resources :users
  
  
  

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { email.downcase! }
  
  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
    
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user=User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      
      #remember user
      
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      
      redirect_to user
    else 
      flash.now[:danger]='Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
 
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)    
    
    if @user.save
      log_in @user
      remember @user
      flash[:success] = "Welcome to the Awesome Blog App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
  
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    #redirect_to(root_url) unless @user == current_user
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(string = "")
        basic_title = "Awesome Blog"
        if string.blank?
          basic_title
        else
          "#{string} | Awesome Blog"
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given user.
    def log_in(user)
      session[:user_id]= user.id
    end
    
    # Remembers a user in a persistent session.
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end

    # Returns true if the given user is the current user.
    # def current_user?(user)
    #   user == current_user
    # end

    # Returns true if the given user is the current user.
    # def current_user
    # @currect_user ||=User.find_by(id:session[:user_id])
    # end
    
    #####Try 2  
    # Returns the user corresponding to the remember token cookie.
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
     !current_user.nil?
    end
    
    # Forgets a persistent session.
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

    # Logs out the current user.
    def log_out
     forget(current_user)
     session.delete(:user_id)
     @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar for the given user.
  
  #Try 2
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  #Try 1
  # def gravatar_for(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This is the footer of the Awesome Blog.
    Training App by (Student Name)
  </small>
  <nav>
    <ul>
     <li class="nav-item">
        <%= link_to "About", about_path %>
      </li>
       <li class="nav-item">
        <%= link_to "Contact", contact_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!DOCTYPE html>

<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <nav class="navbar navbar-toggleable-xl navbar-inverse" style="background: coral;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!--Brand -->
    <a class="navbar-brand" href="#">Awesome Blog</a>
    
    <!--Links -->
    <div class="collapse navbar-collapse justify-content-end" id="nav-content">  
    <ul class="navbar-nav">
      <li class="nav-item">
        <li><%= link_to "Home", root_path %></li>
      </li>
      <li class="nav-item">
        <li><%= link_to "Help", help_path %></li>
      </li>
      
      <% if logged_in? %>
      
      <li><%= link_to "Users", users_path %></li>
      
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      
        <% else %>
        
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
  
    </ul>
  </nav>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<!-- Note:This partial introduces several new Rails and Ruby constructs, including two methods for Rails error objects. The first method is count, which simply returns the number of errors:

>> user.errors.count
=> 2   -->


<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>




<!--<!--% if object.errors.any? %>-->
<!--  <div id="error_explanation">-->
<!--    <div class="alert alert-danger">-->
<!--      The form contains <%= pluralize(object.errors.count, "error") %>.-->
<!--    </div>-->
<!--    <ul>-->
<!--    <!--% object.errors.full_messages.each do |msg| %>-->
<!--      <li><%= msg %></li>-->
<!--    <!--% end %>-->
<!--    </ul>-->
<!--  </div>-->
<!--<!--% end %>-->

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>

<ul class="nav nav-tabs">
	
  <li class="nav-item">
      <a class="nav-link active" href="#">HTML</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" href="#">CSS</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" href="#">JavaScript</a>
  </li>
  
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    Preview
    </a>
    
    <div class="dropdown-menu" aria-labelledby="Preview">
      <a class="dropdown-item" href="#">Mobile Phone</a>
      <a class="dropdown-item" href="#">Tablet</a>
      <a class="dropdown-item" href="#">Laptop</a>
      <a class="dropdown-item" href="#">Desktop</a>
    </div>
  </li>
</ul>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Contact Me at grace.sojor@gmail.com</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help")%>

<h1>Help</h1>
<p>Get help on the Awesome Blog at the _______________. 
For questions, send email at (student email).
</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home")%>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Awesome Blog</title>
  </head>
  <body>
    <div class="center jumbotron">
      <h1>Welcome to the most awesome app!</h1>
      <h2>
        This is the home page for the
        Awesome Blog Application
      </h2>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>

  </body>
</html>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
  <% @users.each do |user| %>
   
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
    
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- Try 1 -->
<!--% provide(:title, 'Sign up') %>-->
<!--<h1>Sign up</h1>-->


<!-- Try 2 -->

<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <!--%= render 'shared/error_messages' %-->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--Try 1-->

    <!--%= @user.name %>, <!--%= @user.email %-->



<!--Try 2-->



<!--Try 3-->
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>